### ISSUE TITLE
Captions on gallery thumbnails

### ISSUE THREAD

**Issue by grzegorzdudek** [staaky/fresco#12]
Is there a way to add captions inside thumbnails in whole gallery view?
![Zrzut ekranu 2021-05-20 214952](https://user-images.githubusercontent.com/72888216/119040166-5b7bef00-b9b5-11eb-997f-421bc5eb1d3c.png)

**Comment by staaky** [comment]
This isn’t Fresco, maybe you’re using some other script that builds on top of it, you’d have to add captions there.

**Comment by grzegorzdudek** [comment]
I see, thanks and sorry for bothering with such a minor issue.

Pozdrawiam
*Grzegorz Dudek*

+48 *693 686 901 * |  grzegorzdudek.com


pt., 21 maj 2021 o 00:26 Nick Stakenburg ***@***.***>
napisał(a):
